LibEBC: TCLAP::CmdLineOutput Class Reference
TCLAP::CmdLineOutput Class Reference abstract
#include <CmdLineOutput.h>
Public Member Functions
virtual ~CmdLineOutput ()
virtual void usage (CmdLineInterface &c)=0
virtual void version (CmdLineInterface &c)=0
virtual void failure (CmdLineInterface &c, ArgException &e)=0
Detailed Description
The interface that any output object must implement.
Constructor & Destructor Documentation
~CmdLineOutput()
virtual TCLAP::CmdLineOutput::~CmdLineOutput () inline virtual
Virtual destructor.
References failure(), usage(), and version().
Member Function Documentation
failure()
virtual void TCLAP::CmdLineOutput::failure (CmdLineInterface & c, ArgException & e) pure virtual
Generates some sort of output for a failure.
Parameters
c - The CmdLine object the output is generated for.
e - The ArgException that caused the failure.
Implemented in TCLAP::ZshCompletionOutput, TCLAP::DocBookOutput, and TCLAP::StdOutput.
Referenced by TCLAP::CmdLine::parse(), and ~CmdLineOutput().
usage()
virtual void TCLAP::CmdLineOutput::usage (CmdLineInterface & c) pure virtual
Generates some sort of output for the USAGE.
Parameters
c - The CmdLine object the output is generated for.
Implemented in TCLAP::ZshCompletionOutput, TCLAP::DocBookOutput, and TCLAP::StdOutput.
Referenced by ~CmdLineOutput().
version()
virtual void TCLAP::CmdLineOutput::version (CmdLineInterface & c) pure virtual
Generates some sort of output for the version.
Parameters
c - The CmdLine object the output is generated for.
Implemented in TCLAP::ZshCompletionOutput, TCLAP::DocBookOutput, and TCLAP::StdOutput.
Referenced by ~CmdLineOutput().
The documentation for this class was generated from the following file:
tool/vendor/tclap/include/tclap/CmdLineOutput.h