LibEBC: ebc::BitcodeContainer Class Reference
ebc::BitcodeContainer Class Reference
#include <BitcodeContainer.h>
Public Member Functions
BitcodeContainer (const char *data, std::uint32_t size)
BitcodeContainer (BitcodeContainer &&bitcodeArchive) noexcept
virtual ~BitcodeContainer ()
virtual bool IsArchive () const
bool IsEmpty () const
const std::vector< std::string > & GetCommands () const
void SetCommands (const std::vector< std::string > &cmd)
BinaryMetadata & GetBinaryMetadata ()
const BinaryMetadata & GetBinaryMetadata () const
virtual std::vector< std::unique_ptr< EmbeddedFile > > GetEmbeddedFiles () const
const std::string & GetPrefix () const
void SetPrefix (std::string prefix)
Protected Member Functions
void SetData (const char *data, std::uint32_t size) noexcept
std::pair< const char *, std::uint32_t > GetData () const
Constructor & Destructor Documentation
ebc::BitcodeContainer::BitcodeContainer (const char * data, std::uint32_t size)
References SetData().
ebc::BitcodeContainer::BitcodeContainer (BitcodeContainer && bitcodeArchive) noexcept
References SetData().
ebc::BitcodeContainer::~BitcodeContainer () virtual
Member Function Documentation
BinaryMetadata & ebc::BitcodeContainer::GetBinaryMetadata ()
Get the binary meta data associated with this bitcode container.
Returns
The binary meta data.
Referenced by ebc::BitcodeRetriever::Impl::GetBitcodeContainers(), ebc::BitcodeArchive::GetMetadata(), and ebc::BitcodeArchive::WriteXarToFile().
const BinaryMetadata & ebc::BitcodeContainer::GetBinaryMetadata () const
Set the binary meta data associated with this bitcode container.
Returns
The binary meta data.
const std::vector< std::string > & ebc::BitcodeContainer::GetCommands () const
Get the commands passed to the compiler front end.
Returns
The commands passed to the compiler front end.
std::pair< const char *, std::uint32_t > ebc::BitcodeContainer::GetData () const protected
Referenced by ebc::BitcodeArchive::GetMetadata(), and ebc::BitcodeArchive::WriteXarToFile().
std::vector< std::unique_ptr< EmbeddedFile > > ebc::BitcodeContainer::GetEmbeddedFiles () const virtual
Extract individual bitcode files from this container and return a vector of file names. This operation can be expensive as it decompresses each bitcode file.
Returns
A vector of bitcode files.
Reimplemented in ebc::BitcodeArchive.
References ebc::EmbeddedFileFactory::CreateEmbeddedFile(), ebc::util::uuid::GenerateUUID(), ebc::util::bitcode::GetBitcodeType(), IsEmpty(), ebc::Unknown, ebc::util::uuid::UuidToString(), and ebc::util::bitcode::WriteToFile().
const std::string & ebc::BitcodeContainer::GetPrefix () const
Referenced by ebc::BitcodeArchive::GetEmbeddedFiles(), ebc::BitcodeArchive::GetMetadata(), and ebc::BitcodeArchive::WriteXarToFile().
bool ebc::BitcodeContainer::IsArchive () const virtual
Indicates whether the given bitcode container is a bitcode archive.
Returns
False.
Reimplemented in ebc::BitcodeArchive.
bool ebc::BitcodeContainer::IsEmpty () const
Indicates whether the given bitcode container is merely a placeholder.
Returns
True if data is empty.
Referenced by ebc::BitcodeArchive::GetEmbeddedFiles(), and GetEmbeddedFiles().
void ebc::BitcodeContainer::SetCommands (const std::vector< std::string > & cmd)
Set the commands passed to the compiler front end.
Parameters
cmd The commands passed to the compiler front end.
Referenced by ebc::BitcodeRetriever::Impl::GetBitcodeContainers().
void ebc::BitcodeContainer::SetData (const char * data, std::uint32_t size) protected noexcept
Referenced by BitcodeContainer().
void ebc::BitcodeContainer::SetPrefix (std::string prefix)
Referenced by main().
The documentation for this class was generated from the following files:
lib/include/ebc/BitcodeContainer.h
lib/src/BitcodeContainer.cpp