LibEBC: ebc::BitcodeRetriever Class Reference
ebc::BitcodeRetriever Class Reference
Retrieves bitcode form an object file.
#include <BitcodeRetriever.h>
Public Member Functions
BitcodeRetriever (std::string objectPath)
void SetArch (std::string arch)
std::vector< std::unique_ptr< BitcodeContainer > > GetBitcodeContainers ()
Detailed Description
Retrieves bitcode form an object file.
Constructor & Destructor Documentation
BitcodeRetriever()
ebc::BitcodeRetriever::BitcodeRetriever (std::string objectPath)
Creates an instance of the bitcode retriever for the given object file.
Parameters
objectPath The file from which to retrieve bitcode.
Member Function Documentation
GetBitcodeContainers()
std::vector< std::unique_ptr< BitcodeContainer > > ebc::BitcodeRetriever::GetBitcodeContainers ()
Perform the actual bitcode retrieval. Depending on the type of the object file the resulting list contains plain bitcode containers or bitcode archives.
Returns
A list of bitcode containers.
References ebc::BitcodeContainer::GetBinaryMetadata(), ebc::BinaryMetadata::SetArch(), ebc::BitcodeContainer::SetCommands(), ebc::BinaryMetadata::SetFileFormatName(), ebc::BinaryMetadata::SetFileName(), and ebc::BinaryMetadata::SetUuid().
SetArch()
void ebc::BitcodeRetriever::SetArch (std::string arch)
Set the architecture for which to retrieve bitcode. This is relevant to 'fat' object files containing multiple architectures. If no architecture is set, bitcode is retrieved for all present architectures.
Parameters
arch The architecture.
Referenced by main().
The documentation for this class was generated from the following files:
lib/include/ebc/BitcodeRetriever.h
lib/src/BitcodeRetriever.cpp