LibEBC: ebc::BitcodeArchive Class Reference
ebc::BitcodeArchive Class Reference
#include <BitcodeArchive.h>
Public Member Functions
BitcodeArchive (const char *data, std::uint32_t size)
BitcodeArchive (BitcodeArchive &&bitcodeArchive) noexcept
virtual bool IsArchive () const override
std::string WriteXarToFile (std::string fileName="") const
const BitcodeMetadata & GetMetadata () const
std::vector< BitcodeFile > GetBitcodeFiles (bool extract=false) const override
Public Member Functions inherited from ebc::BitcodeContainer
BitcodeContainer (const char *data, std::uint32_t size)
BitcodeContainer (BitcodeContainer &&bitcodeArchive) noexcept
virtual ~BitcodeContainer ()
const std::vector< std::string > & GetCommands () const
void SetCommands (const std::vector< std::string > &cmd)
BinaryMetadata & GetBinaryMetadata ()
const BinaryMetadata & GetBinaryMetadata () const
Additional Inherited Members
Protected Member Functions inherited from ebc::BitcodeContainer
void SetData (const char *data, std::uint32_t size) noexcept
std::pair< const char *, std::uint32_t > GetData () const
Detailed Description
A bitcode archive is a special kind of bitcode container created by Apple's version of LLVM. It contains a XAR archive with the (unlinked) bitcode files. Additional metadata is part of the archive's table of content.
Constructor & Destructor Documentation
BitcodeArchive() [1/2]
ebc::BitcodeArchive::BitcodeArchive (const char * data, std::uint32_t size)
BitcodeArchive() [2/2]
ebc::BitcodeArchive::BitcodeArchive (BitcodeArchive && bitcodeArchive) noexcept
Member Function Documentation
GetBitcodeFiles()
std::vector< BitcodeFile > ebc::BitcodeArchive::GetBitcodeFiles (bool extract = false) const override virtual
Extract individual bitcode files from this archive and return a vector of file names. This operation can be expensive as it decompresses each bitcode file. The result is empty if not compiled with xar support.
Parameters
extract Optional paramter indicating whether different bitcode files should be extracted and written to file.
Returns
A vector of bitcode files.
Reimplemented from ebc::BitcodeContainer.
References ebc::util::Namer::GetFileName(), and WriteXarToFile().
GetMetadata()
const BitcodeMetadata & ebc::BitcodeArchive::GetMetadata () const
Return the MetaData contained in this bitcode archive. This operation is cheap as the heavy lifting occurs at construction time. Metadata is empty if not compiled with xar support.
Returns
The meta data.
References ebc::BitcodeContainer::GetBinaryMetadata(), ebc::BitcodeContainer::GetData(), ebc::BinaryMetadata::GetFileFormatName(), and WriteXarToFile().
IsArchive()
bool ebc::BitcodeArchive::IsArchive () const override virtual
Indicates whether the given bitcode container is a bitcode archive.
Returns
True.
Reimplemented from ebc::BitcodeContainer.
WriteXarToFile()
std::string ebc::BitcodeArchive::WriteXarToFile (std::string fileName = "") const
Write container data to file. If no file name is provided, the file format name of the binary will be used, followed by the xar extension. This works even when compiled without xar support.
Parameters
fileName Optional file name for the XAR archive.
Returns
The path to the XAR archive file.
References ebc::BitcodeContainer::GetBinaryMetadata(), ebc::BitcodeContainer::GetData(), ebc::BinaryMetadata::GetFileName(), and ebc::util::bitcode::WriteFile().
Referenced by GetBitcodeFiles(), and GetMetadata().
The documentation for this class was generated from the following files:
lib/include/ebc/BitcodeArchive.h
lib/src/BitcodeArchive.cpp