LibEBC: TCLAP::UnlabeledMultiArg< T > Class Template Reference
TCLAP::UnlabeledMultiArg< T > Class Template Reference
#include <UnlabeledMultiArg.h>
Public Member Functions
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, bool ignoreable=false, Visitor *v=NULL)
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, CmdLineInterface &parser, bool ignoreable=false, Visitor *v=NULL)
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, Constraint< T > *constraint, bool ignoreable=false, Visitor *v=NULL)
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, Constraint< T > *constraint, CmdLineInterface &parser, bool ignoreable=false, Visitor *v=NULL)
virtual bool processArg (int *i, std::vector< std::string > &args)
virtual std::string shortID (const std::string &val="val") const
virtual std::string longID (const std::string &val="val") const
virtual bool operator== (const Arg &a) const
virtual void addToList (std::list< Arg *> &argList) const
Public Member Functions inherited from TCLAP::MultiArg< T >
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, Visitor *v=NULL)
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, CmdLineInterface &parser, Visitor *v=NULL)
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, Constraint< T > *constraint, Visitor *v=NULL)
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, Constraint< T > *constraint, CmdLineInterface &parser, Visitor *v=NULL)
const std::vector< T > & getValue ()
const_iterator begin () const
const_iterator end () const
virtual bool isRequired () const
virtual bool allowMore ()
virtual void reset ()
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
const std::string & getFlag () const
const std::string & getName () const
std::string getDescription () const
void forceRequired ()
void xorSet ()
bool isValueRequired () const
bool isSet () const
bool isIgnoreable () const
virtual bool argMatches (const std::string &s) const
virtual std::string toString () const
virtual void trimFlag (std::string &flag, std::string &value) const
bool _hasBlanks (const std::string &s) const
void setRequireLabel (const std::string &s)
virtual bool acceptsMultipleValues ()
Additional Inherited Members
Public Types inherited from TCLAP::MultiArg< T >
typedef std::vector< T > container_type
typedef container_type::iterator iterator
typedef container_type::const_iterator const_iterator
Static Public Member Functions inherited from TCLAP::Arg
static void beginIgnoring ()
static bool ignoreRest ()
static char delimiter ()
static char blankChar ()
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
static void setDelimiter (char c)
Protected Member Functions inherited from TCLAP::MultiArg< T >
void _extractValue (const std::string &val)
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Protected Attributes inherited from TCLAP::MultiArg< T >
std::vector< T > _values
std::string _typeDesc
Constraint< T > * _constraint
bool _allowMore
Protected Attributes inherited from TCLAP::Arg
std::string _flag
std::string _name
std::string _description
bool _required
std::string _requireLabel
bool _valueRequired
bool _alreadySet
Visitor * _visitor
bool _ignoreable
bool _xorSet
bool _acceptsMultipleValues
Detailed Description
template<class T>
class TCLAP::UnlabeledMultiArg< T >
Just like a MultiArg, except that the arguments are unlabeled. Basically, this Arg will slurp up everything that hasn't been matched to another Arg.
Constructor & Destructor Documentation
UnlabeledMultiArg() [1/4]
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
UnlabeledMultiArg() [2/4]
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, CmdLineInterface & parser, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
parser - A CmdLine parser object to add this Arg to
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
References TCLAP::Arg::_ignoreable, TCLAP::CmdLineInterface::add(), TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
UnlabeledMultiArg() [3/4]
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, Constraint< T > * constraint, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
UnlabeledMultiArg() [4/4]
template<class T > TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, Constraint< T > * constraint, CmdLineInterface & parser, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
parser - A CmdLine parser object to add this Arg to
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
References TCLAP::Arg::_ignoreable, TCLAP::CmdLineInterface::add(), TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
Member Function Documentation
addToList()
template<class T > void TCLAP::UnlabeledMultiArg< T >::addToList (std::list< Arg *> & argList) const virtual
Pushes this to back of list rather than front.
Parameters
argList - The list this should be added to.
Reimplemented from TCLAP::Arg.
longID()
template<class T > std::string TCLAP::UnlabeledMultiArg< T >::longID (const std::string & val = "val") const virtual
Returns the a long id string. Used in the usage.
Parameters
val - value to be used.
Reimplemented from TCLAP::MultiArg< T >.
References TCLAP::MultiArg< T >::_typeDesc.
operator==()
template<class T > bool TCLAP::UnlabeledMultiArg< T >::operator== (const Arg & a) const virtual
Opertor ==.
Parameters
a - The Arg to be compared to this.
Reimplemented from TCLAP::Arg.
References TCLAP::Arg::_description, TCLAP::Arg::_name, TCLAP::Arg::getDescription(), and TCLAP::Arg::getName().
processArg()
template<class T > bool TCLAP::UnlabeledMultiArg< T >::processArg (int * i, std::vector< std::string > & args) virtual
Handles the processing of the argument. This re-implements the Arg version of this method to set the _value of the argument appropriately. It knows the difference between labeled and unlabeled.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed from main().
Reimplemented from TCLAP::MultiArg< T >.
References TCLAP::Arg::_alreadySet, TCLAP::MultiArg< T >::_extractValue(), and TCLAP::Arg::_hasBlanks().
shortID()
template<class T > std::string TCLAP::UnlabeledMultiArg< T >::shortID (const std::string & val = "val") const virtual
Returns the a short id string. Used in the usage.
Parameters
val - value to be used.
Reimplemented from TCLAP::MultiArg< T >.
References TCLAP::MultiArg< T >::_typeDesc.
The documentation for this class was generated from the following file:
tool/vendor/tclap/include/tclap/UnlabeledMultiArg.h