LibEBC: ebc::util::Namer Class Reference
ebc::util::Namer Class Reference
#include <Namer.h>
Public Member Functions
Namer ()=delete
Static Public Member Functions
static std::string GetFileName ()
static void SetPath (std::string path)
static void SetPrefix (std::string prefix)
Detailed Description
Static class for generating unique file names with a monotonically increasing number.
Constructor & Destructor Documentation
Namer()
ebc::util::Namer::Namer () delete
Member Function Documentation
GetFileName()
std::string ebc::util::Namer::GetFileName () static
Get a new unique file name. The file name number increases by one after this call.
Returns
A guaranteed unique file name.
Referenced by ebc::BitcodeArchive::GetBitcodeFiles(), and ebc::BitcodeContainer::GetBitcodeFiles().
SetPath()
void ebc::util::Namer::SetPath (std::string path) static
Set a destination directory path.
Parameters
path Destination directory path.
Referenced by main().
SetPrefix()
void ebc::util::Namer::SetPrefix (std::string prefix) static
Set a global file name prefix. All subsequent file names will start with this prefix.
Parameters
prefix The desired file name prefix.
Referenced by main().
The documentation for this class was generated from the following files:
lib/include/ebc/util/Namer.h
lib/src/util/Namer.cpp