LibEBC: ebc::BinaryMetadata Class Reference
ebc::BinaryMetadata Class Reference
Abstraction of the meta data linked to a binary object or archive.
#include <BinaryMetadata.h>
Public Member Functions
std::string GetFileFormatName () const
void SetFileFormatName (std::string fileFormatName)
std::string GetFileName () const
void SetFileName (std::string fileName)
std::string GetArch () const
void SetArch (std::string arch)
std::string GetUUID () const
void SetUuid (const std::uint8_t *uuid)
Detailed Description
Abstraction of the meta data linked to a binary object or archive.
Member Function Documentation
GetArch()
std::string ebc::BinaryMetadata::GetArch () const
GetFileFormatName()
std::string ebc::BinaryMetadata::GetFileFormatName () const
Referenced by ebc::BitcodeArchive::GetMetadata().
GetFileName()
std::string ebc::BinaryMetadata::GetFileName () const
Referenced by ebc::BitcodeArchive::WriteXarToFile().
GetUUID()
std::string ebc::BinaryMetadata::GetUUID () const
References ebc::util::uuid::UuidToString().
SetArch()
void ebc::BinaryMetadata::SetArch (std::string arch)
Referenced by ebc::BitcodeRetriever::GetBitcodeContainers().
SetFileFormatName()
void ebc::BinaryMetadata::SetFileFormatName (std::string fileFormatName)
Referenced by ebc::BitcodeRetriever::GetBitcodeContainers().
SetFileName()
void ebc::BinaryMetadata::SetFileName (std::string fileName)
Referenced by ebc::BitcodeRetriever::GetBitcodeContainers().
SetUuid()
void ebc::BinaryMetadata::SetUuid (const std::uint8_t * uuid)
Referenced by ebc::BitcodeRetriever::GetBitcodeContainers().
The documentation for this class was generated from the following files:
lib/include/ebc/BinaryMetadata.h
lib/src/BinaryMetadata.cpp