LibEBC: TCLAP::ValuesConstraint< T > Class Template Reference
TCLAP::ValuesConstraint< T > Class Template Reference
#include <ValuesConstraint.h>
Public Member Functions
ValuesConstraint (std::vector< T > &allowed)
virtual ~ValuesConstraint ()
virtual std::string description () const
virtual std::string shortID () const
virtual bool check (const T &value) const
Public Member Functions inherited from TCLAP::Constraint< T >
virtual ~Constraint ()
Protected Attributes
std::vector< T > _allowed
std::string _typeDesc
Detailed Description
template<class T>
class TCLAP::ValuesConstraint< T >
A Constraint that constrains the Arg to only those values specified in the constraint.
Constructor & Destructor Documentation
ValuesConstraint()
template<class T > TCLAP::ValuesConstraint< T >::ValuesConstraint (std::vector< T > & allowed)
Constructor.
Parameters
allowed - vector of allowed values.
References TCLAP::ValuesConstraint< T >::_allowed, and TCLAP::ValuesConstraint< T >::_typeDesc.
~ValuesConstraint()
template<class T > virtual TCLAP::ValuesConstraint< T >::~ValuesConstraint () inline virtual
Virtual destructor.
References TCLAP::ValuesConstraint< T >::check(), TCLAP::ValuesConstraint< T >::description(), and TCLAP::ValuesConstraint< T >::shortID().
Member Function Documentation
check()
template<class T > bool TCLAP::ValuesConstraint< T >::check (const T & value) const virtual
The method used to verify that the value parsed from the command line meets the constraint.
Parameters
value - The value that will be checked.
Implements TCLAP::Constraint< T >.
References TCLAP::ValuesConstraint< T >::_allowed.
Referenced by TCLAP::ValuesConstraint< T >::~ValuesConstraint().
description()
template<class T > std::string TCLAP::ValuesConstraint< T >::description () const virtual
Returns a description of the Constraint.
Implements TCLAP::Constraint< T >.
References TCLAP::ValuesConstraint< T >::_typeDesc.
Referenced by TCLAP::ValuesConstraint< T >::~ValuesConstraint().
shortID()
template<class T > std::string TCLAP::ValuesConstraint< T >::shortID () const virtual
Returns the short ID for the Constraint.
Implements TCLAP::Constraint< T >.
References TCLAP::ValuesConstraint< T >::_typeDesc.
Referenced by TCLAP::ValuesConstraint< T >::~ValuesConstraint().
Member Data Documentation
_allowed
template<class T > std::vector<T> TCLAP::ValuesConstraint< T >::_allowed protected
The list of valid values.
Referenced by TCLAP::ValuesConstraint< T >::check(), and TCLAP::ValuesConstraint< T >::ValuesConstraint().
_typeDesc
template<class T > std::string TCLAP::ValuesConstraint< T >::_typeDesc protected
The string used to describe the allowed values of this constraint.
Referenced by TCLAP::ValuesConstraint< T >::description(), TCLAP::ValuesConstraint< T >::shortID(), and TCLAP::ValuesConstraint< T >::ValuesConstraint().
The documentation for this class was generated from the following file:
tool/vendor/tclap/include/tclap/ValuesConstraint.h