LibEBC: ebc::EmbeddedFileFactory Class Reference
ebc::EmbeddedFileFactory Class Reference
#include <EmbeddedFileFactory.h>
Static Public Member Functions
static std::unique_ptr< EmbeddedFile > CreateEmbeddedFile (std::string file)
Member Function Documentation
std::unique_ptr< EmbeddedFile > ebc::EmbeddedFileFactory::CreateEmbeddedFile (std::string file) static
References ebc::util::bitcode::GetBitcodeType(), ebc::util::macho::IsMachOFile(), ebc::util::xar::IsXarFile(), and ebc::Unknown.
Referenced by ebc::BitcodeArchive::GetEmbeddedFiles(), and ebc::BitcodeContainer::GetEmbeddedFiles().
The documentation for this class was generated from the following files:
lib/include/ebc/EmbeddedFileFactory.h
lib/src/EmbeddedFileFactory.cpp