LibEBC: ebc::BitcodeMetadata Class Reference
ebc::BitcodeMetadata Class Reference
#include <BitcodeMetadata.h>
Public Member Functions
BitcodeMetadata (std::string xml)
BitcodeMetadata (const BitcodeMetadata &bitcodeTOC)=delete
~BitcodeMetadata ()
const std::string & GetXml () const
std::vector< std::string > GetDylibs () const
std::vector< std::string > GetLinkOptions () const
std::vector< std::string > GetClangCommands (std::string fileName) const
std::vector< std::string > GetSwiftCommands (std::string fileName) const
Detailed Description
Abstraction of bitcode meta data associated with a BitcodeArchive. The data comes from the table of content of the embedded XAR archive.
Constructor & Destructor Documentation
BitcodeMetadata() [1/2]
ebc::BitcodeMetadata::BitcodeMetadata (std::string xml)
BitcodeMetadata() [2/2]
ebc::BitcodeMetadata::BitcodeMetadata (const BitcodeMetadata & bitcodeTOC) delete
~BitcodeMetadata()
ebc::BitcodeMetadata::~BitcodeMetadata ()
Member Function Documentation
GetClangCommands()
std::vector< std::string > ebc::BitcodeMetadata::GetClangCommands (std::string fileName) const
Get the commands passed to clang for the given file.
Parameters
fileName The input file passed to the clang compiler.
Returns
The comands passed to the clang front end for the given file.
GetDylibs()
std::vector< std::string > ebc::BitcodeMetadata::GetDylibs () const
Get dynamic libraries used for linking.
Returns
A vector of strings with the name of the dylibs this binary was linked against.
References ebc::util::xml::FindNodeWithName(), and ebc::util::xml::GetTextFromNodesWithName().
GetLinkOptions()
std::vector< std::string > ebc::BitcodeMetadata::GetLinkOptions () const
Get options passed to linker.
Returns
A list of strings with the options passed to the linker.
References ebc::util::xml::FindNodeWithName(), ebc::util::xml::FindNodeWithNameAndContent(), and ebc::util::xml::GetTextFromNodesWithName().
GetSwiftCommands()
std::vector< std::string > ebc::BitcodeMetadata::GetSwiftCommands (std::string fileName) const
Get the commands passed to swiftc for the given file.
Parameters
fileName The input file passed to the swift compiler.
Returns
The comands passed to the swift front end for the given file.
GetXml()
const std::string & ebc::BitcodeMetadata::GetXml () const
Returns the meta data as XML string.
Returns
The XML data as a string.
The documentation for this class was generated from the following files:
lib/include/ebc/BitcodeMetadata.h
lib/src/BitcodeMetadata.cpp