LibEBC: ebc::BitcodeRetriever::Impl Class Reference
ebc::BitcodeRetriever::Impl Class Reference
Public Types
typedef std::vector< std::unique_ptr< BitcodeContainer > > BitcodeContainers
Public Member Functions
Impl (std::string objectPath)
void SetArch (std::string arch)
BitcodeContainers GetBitcodeContainers ()
Member Typedef Documentation
typedef std::vector<std::unique_ptr<BitcodeContainer> > ebc::BitcodeRetriever::Impl::BitcodeContainers
Constructor & Destructor Documentation
ebc::BitcodeRetriever::Impl::Impl (std::string objectPath) inline
Member Function Documentation
BitcodeContainers ebc::BitcodeRetriever::Impl::GetBitcodeContainers () inline
Perform the actual bitcode retrieval. Depending on the type of the object file the resulting list contains plain bitcode containers or bitcode archives.
Returns
A list of bitcode containers.
References ebc::BitcodeContainer::GetBinaryMetadata(), ebc::BinaryMetadata::SetArch(), ebc::BitcodeContainer::SetCommands(), ebc::BinaryMetadata::SetFileFormatName(), ebc::BinaryMetadata::SetFileName(), and ebc::BinaryMetadata::SetUuid().
void ebc::BitcodeRetriever::Impl::SetArch (std::string arch) inline
Set the architecture for which to retrieve bitcode. This is relevant to 'fat' object files containing multiple architectures. If no architecture is set, bitcode is retrieved for all present architectures.
The documentation for this class was generated from the following file:
lib/src/BitcodeRetriever.cpp