LibEBC: tool/ebcutil.cpp File Reference
ebcutil.cpp File Reference
#include "ebc/BitcodeArchive.h"
#include "ebc/BitcodeContainer.h"
#include "ebc/BitcodeFile.h"
#include "ebc/BitcodeMetadata.h"
#include "ebc/BitcodeRetriever.h"
#include "ebc/util/Namer.h"
#include <tclap/CmdLine.h>
#include <iomanip>
#include <iostream>
Functions
int main (int argc, char *argv[])
Variables
constexpr int WIDTH = 12
constexpr int WIDTH_NESTED = 14
Function Documentation
main()
int main (int argc, char * argv[])
References TCLAP::CmdLine::add(), TCLAP::SwitchArg::getValue(), TCLAP::ValueArg< T >::getValue(), TCLAP::Arg::isSet(), TCLAP::CmdLine::parse(), ebc::BitcodeRetriever::SetArch(), ebc::util::Namer::SetPath(), and ebc::util::Namer::SetPrefix().
Variable Documentation
WIDTH
constexpr int WIDTH = 12
WIDTH_NESTED
constexpr int WIDTH_NESTED = 14