LibEBC: ebc::util::uuid Namespace Reference
ebc::util::uuid Namespace Reference
Functions
std::string UuidToString (std::array< std::uint8_t, 16 > uuid)
Convert UUID to canonical format with hyphens.
std::array< std::uint8_t, 16 > GenerateUUID ()
Generate a random UUID.
Function Documentation
std::array< std::uint8_t, 16 > ebc::util::uuid::GenerateUUID ()
Generate a random UUID.
Referenced by ebc::util::xar::Extract(), and ebc::BitcodeContainer::GetEmbeddedFiles().
std::string ebc::util::uuid::UuidToString (std::array< std::uint8_t, 16 > uuid)
Convert UUID to canonical format with hyphens.
Referenced by ebc::util::xar::Extract(), ebc::BitcodeContainer::GetEmbeddedFiles(), and ebc::BinaryMetadata::GetUUID().