LibEBC: ebc::util::bitcode Namespace Reference
ebc::util::bitcode Namespace Reference
Functions
BitcodeType GetBitcodeType (std::uint64_t magic)
BitcodeType GetBitcodeType (std::string file)
void WriteToFile (const char *data, std::uint32_t size, std::string file)
Function Documentation
BitcodeType ebc::util::bitcode::GetBitcodeType (std::uint64_t magic)
References ebc::Bitcode, ebc::BitcodeWrapper, ebc::IR, and ebc::Unknown.
Referenced by ebc::EmbeddedFileFactory::CreateEmbeddedFile(), GetBitcodeType(), and ebc::BitcodeContainer::GetEmbeddedFiles().
BitcodeType ebc::util::bitcode::GetBitcodeType (std::string file)
Returns true if the first four bytes fo the given file match the LLVM bitcode magic number.
Parameters
file Path to the file to check.
Returns
True if the magic number BC 0xC0DE is found.
References GetBitcodeType(), and ebc::Unknown.
void ebc::util::bitcode::WriteToFile (const char * data, std::uint32_t size, std::string file)
Write data to file with given file name.
Parameters
data Bitcode binary data.
size Bitcode binary data size.
fileName The desired filename for the bitcode file.
Referenced by ebc::BitcodeContainer::GetEmbeddedFiles(), and ebc::BitcodeArchive::WriteXarToFile().