LibEBC: ebc::util::xml Namespace Reference
ebc::util::xml Namespace Reference
Classes
class XmlInitialization
Functions
std::string GetContent (_xmlNode *node)
_xmlNode * FindNodeWithName (_xmlNode *root, std::string name)
_xmlNode * FindNodeWithNameAndContent (_xmlNode *root, std::string name, std::string content)
std::vector< std::string > GetTextFromNodesWithName (_xmlNode *root, std::string name)
std::string GetContent (xmlNode *node)
xmlNode * FindNodeWithName (xmlNode *root, std::string name)
xmlNode * FindNodeWithNameAndContent (xmlNode *root, std::string name, std::string content)
std::vector< std::string > GetTextFromNodesWithName (xmlNode *root, std::string name)
Variables
XmlInitialization xmlInitialization
Function Documentation
FindNodeWithName() [1/2]
xmlNode* ebc::util::xml::FindNodeWithName (xmlNode * root, std::string name)
References FindNodeWithName().
FindNodeWithName() [2/2]
_xmlNode* ebc::util::xml::FindNodeWithName (_xmlNode * root, std::string name)
Finds the first node at the same level or under the given root that has the given name.
Parameters
root The node where the search starts. Nodes at the same level of the root are considered.
name The name of the desired node.
Returns
The first XML node encountered with the given name. Nullptr if none is found.
Referenced by FindNodeWithName(), ebc::BitcodeMetadata::GetDylibs(), and ebc::BitcodeMetadata::GetLinkOptions().
FindNodeWithNameAndContent() [1/2]
xmlNode* ebc::util::xml::FindNodeWithNameAndContent (xmlNode * root, std::string name, std::string content)
References FindNodeWithNameAndContent(), and GetContent().
FindNodeWithNameAndContent() [2/2]
_xmlNode* ebc::util::xml::FindNodeWithNameAndContent (_xmlNode * root, std::string name, std::string content)
Finds the first node at the same level or under the given root that has the given name and content.
Parameters
root The node where the search starts. Nodes on the same level are not considered.
name The name of the desired node.
content The content of the desired node.
Returns
The first node matching the given criteria. Nullptr if none is found.
Referenced by FindNodeWithNameAndContent(), and ebc::BitcodeMetadata::GetLinkOptions().
GetContent() [1/2]
std::string ebc::util::xml::GetContent (xmlNode * node)
GetContent() [2/2]
std::string ebc::util::xml::GetContent (_xmlNode * node)
Get the content of an XML node as string.
Parameters
node The XML node.
Returns
The content of the given node.
Referenced by FindNodeWithNameAndContent(), and GetTextFromNodesWithName().
GetTextFromNodesWithName() [1/2]
std::vector<std::string> ebc::util::xml::GetTextFromNodesWithName (xmlNode * root, std::string name)
References GetContent().
GetTextFromNodesWithName() [2/2]
std::vector<std::string> ebc::util::xml::GetTextFromNodesWithName (_xmlNode * root, std::string name)
Get the content of each node with the given name at the same level of the given root node.
Parameters
root The node where the search starts. Nodes on the same level are considered.
name The name of the desired node.
Returns
The content of each node matching the criteria.
Referenced by ebc::BitcodeMetadata::GetDylibs(), and ebc::BitcodeMetadata::GetLinkOptions().
Variable Documentation
xmlInitialization
XmlInitialization ebc::util::xml::xmlInitialization